services:
  app:
    image: '9220f23e444c'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=Chelovek051403
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=djavakafka@gmail.com
      - SPRING_MAIL_PASSWORD=tbcn yisj njad qbnl
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - JWT_SECRET=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      - JWT_LIFETIME=PT1H
      - ADMIN_EMAIL=djavakafka@gmail.com
    depends_on:
      - db
      - kafka
    networks:
      - app_network

  db:
    image: 'postgres:17'
    container_name: db
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Chelovek051403
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    expose:
      - '9092'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LOG_DIRS=/opt/bitnami/kafka/data
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app_network

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    expose:
      - '2181'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: